import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import ".././globals.css";
import Navbar from "../components/utilities/Navbar/Navbar";
import Footer from "../components/utilities/Footer/Footer";
import ProgressProvider from "../provider";
import { Suspense } from "react";
// import { AuthProvider } from "../../context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"], // Tentukan weight yang Anda butuhkan
  style: ["normal", "italic"], // Tentukan style yang Anda butuhkan
  // Variabel CSS untuk font
  variable: "--font-inter",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Streaming | myplay",
  description: "Generated by Streaming by myplayground",
};

export default function MoviesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
      <section className={inter.className} style={{ minHeight: "100vh" }}>
        <Suspense>
          <ProgressProvider />
        </Suspense>
        <Navbar />
        {children}
        <Footer />
      </section>
    // </html>
  );
}
