import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import Navbar from "./components/utilities/Navbar/Navbar";
import "./globals.css";
import Footer from "./components/utilities/Footer/Footer";
import ProgressProvider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"], // Tentukan weight yang Anda butuhkan
  style: ["normal", "italic"], // Tentukan style yang Anda butuhkan
  // Variabel CSS untuk font
  variable: "--font-inter",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Streaming | myplay",
  description: "Generated by Streaming by myplayground",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ minHeight: "100vh" }}>
        <ProgressProvider />
        <div className="">{children}</div>
      </body>
    </html>
  );
}
